### ISSUE TITLE
Voicelines + VL Ideas

### ISSUE THREAD

**Issue by AtlasAlexander** [AtlasAlexander/Pixel-Playgroud-Repo#43]

**Comment by LiamSymes** [comment]
Introduction/cutscene voice lines

**Comment by LiamSymes** [comment]
**Damage/Death voice lines:**
1. **[Laser killing player]** -  (Cartoony scream/noise of being zapped), (Grandpa saying a sarcastic line "You're meant to avoid the death beams y'know")
2. **[Player dying X amount of times in a time span or level]** - (Grandpa: "CMON YOU CAN DO IT MY BOY"), (Player dies after that voice line. Grandpa: "Maybe not".)

**Comment by LiamSymes** [comment]
**Grandpa giving hints**:
1. **[When player dies too many times on a certain level]** - (Grandpa: Hint) 
2. **[When player enters a level]** - (Grandpa: Hint)
